<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\lib\ZstdSharp\src\ZstdSharp\ZstdSharp.csproj" />
    <ProjectReference Include="..\..\lib\BymlSharp\src\BymlSharp\BymlSharp.csproj" />
    <ProjectReference Include="..\..\lib\Yaz0Sharp\src\Yaz0Sharp\Yaz0Sharp.csproj" />
  </ItemGroup>

</Project>
