"""Builds the executable patch for the Ganon beam mod (TotK 1.2.1 `main`), as a .pchtxt and an IPS32 file.

What it patches. ShootControllerToggle's update (0x710174694c) starts with `bl 0x7101743ea8` (an occlusion test). That call becomes
`bl cave`; the cave sits in the zero padding at the end of .text, grows the beam's range for our actor only, and then tail-calls the original
function (`b 0x7101743ea8`; x0, x1 and lr are untouched), so the occlusion test itself is never changed, for any beam.

  * Range growth. The controller caches BeamRadiusScale at this+0xa4; our actor's blackboard sets it to the marker value 0.500123 (vanilla
    beams use whole numbers), so every other controller goes straight to the original function. For the marker, each frame
        this+0x98 (the ray length) = min(TARGET, max(this+0x9c, 0) + STEP)
    where this+0x9c is the previous frame's measured length (the start function sets it to -100 each shot, so the beam grows from zero
    every shot, and after a hit it grows from the hit distance).

usage: make_exefs_patch.py <TotK main> <out dir> [step m/frame] [target m]
"""
import struct
import sys

import capstone
import keystone

sys.path.insert(0, "C:/Users/dylan/AppData/Local/Temp/claude/C--Users-dylan-repos-Nintending-Libraries-PtclSharp/4e6b7b11-8efe-4d16-9b29-32209b0df7eb/scratchpad")
import nso  # noqa: E402  (the scratch NSO loader)

main_path, out_dir = sys.argv[1], sys.argv[2]
STEP = float(sys.argv[3]) if len(sys.argv) > 3 else 10.0
TARGET = float(sys.argv[4]) if len(sys.argv) > 4 else 300.0
MARKER = 0.500123

ORIGINAL = 0x1743ea8      # the occlusion test the hook used to call
HOOK = 0x1746984          # text offset of `bl 0x7101743ea8` in the Toggle update
EXPECT_OLD = bytes.fromhex("49f5ff97")
text = nso.load(main_path)[0][1]
assert text[HOOK:HOOK + 4] == EXPECT_OLD, "unexpected instruction at the hook: wrong executable version"
CAVE = (len(text) + 15) & ~15          # first 16-byte boundary after the text file bytes (the page padding is zero)
assert CAVE + 0x80 <= 0x2b1a000, "no room in the last text page"


def f32_bits(x):
    return struct.unpack("<I", struct.pack("<f", x))[0]


def movs(reg, bits):
    return f"movz {reg}, #{bits & 0xffff}\n movk {reg}, #{bits >> 16}, lsl #16\n"


ks = keystone.Ks(keystone.KS_ARCH_ARM64, keystone.KS_MODE_LITTLE_ENDIAN)
head_len = 5 * 4                         # ldr, movz, movk, cmp, b.ne
body = "\n".join([
    "ldr s0, [x19, #0x9c]", "fmov s1, wzr", "fcmp s0, s1", "fcsel s0, s0, s1, gt",
    movs("w8", f32_bits(STEP)), "fmov s2, w8", "fadd s0, s0, s2",
    movs("w8", f32_bits(TARGET)), "fmov s3, w8", "fcmp s0, s3", "fcsel s0, s0, s3, mi",
    "str s0, [x19, #0x98]",
])
body_bytes = bytes(ks.asm(body, CAVE + head_len)[0])
tail = CAVE + head_len + len(body_bytes)  # `b <original occlusion test>`: every beam, ours included, still runs the unmodified function
head = "\n".join(["ldr w8, [x19, #0xa4]", movs("w9", f32_bits(MARKER)), "cmp w8, w9", f"b.ne #{tail}"])
head_bytes = bytes(ks.asm(head, CAVE)[0])
assert len(head_bytes) == head_len
cave_bytes = head_bytes + body_bytes + bytes(ks.asm(f"b #{ORIGINAL}", tail)[0])
bl_bytes = bytes(ks.asm(f"bl {CAVE}", HOOK)[0])

md = capstone.Cs(capstone.CS_ARCH_ARM64, capstone.CS_MODE_ARM)
print("hook:")
for i in md.disasm(bl_bytes, HOOK):
    print(f"  {i.address:#x}: {i.mnemonic} {i.op_str}")
print("cave:")
for i in md.disasm(cave_bytes, CAVE):
    print(f"  {i.address:#x}: {i.mnemonic} {i.op_str}")
print(f"cave {CAVE:#x}, {len(cave_bytes)} bytes; step {STEP}, target {TARGET}, marker {MARKER} = {f32_bits(MARKER):#x}")

build_id = open(main_path, "rb").read()[0x40:0x60].hex().upper()
sbid = build_id.rstrip("0")
pch = f"""@nsobid-{sbid}

# Ganon beam mod, TotK 1.2.1 main (generated by tools/TotkModKit/scripts/make_exefs_patch.py).
# ShootControllerToggle update (0x710174694c): the call to the occlusion test at 0x7101746984 becomes a call to a cave placed in the zero
# padding at the end of .text ({CAVE:#x}). For the controller whose BeamRadiusScale is the marker {MARKER} (only the Ganon beam actor) the
# cave grows the ray length by {STEP} m per frame up to {TARGET} m; then, for every beam, it jumps to the original occlusion test unchanged.
@flag offset_shift 0x100

@enabled
{HOOK:08X} {bl_bytes.hex().upper()}
{CAVE:08X} {cave_bytes.hex().upper()}
@stop
"""
import os
os.makedirs(out_dir, exist_ok=True)
open(os.path.join(out_dir, "GanonBeastBeam.pchtxt"), "w", newline="\n").write(pch)
ips = b"IPS32"
for off, data in ((HOOK, bl_bytes), (CAVE, cave_bytes)):
    ips += struct.pack(">I", off + 0x100) + struct.pack(">H", len(data)) + data
ips += b"EEOF"
open(os.path.join(out_dir, build_id + ".ips"), "wb").write(ips)
print("wrote", out_dir)
