<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PtclSharp\PtclSharp.csproj" />
    <ProjectReference Include="..\..\lib\BntxSharp\src\BntxSharp\BntxSharp.csproj" />
    <ProjectReference Include="..\..\lib\TxtgSharp\src\TxtgSharp\TxtgSharp.csproj" />
  </ItemGroup>

</Project>
